### ISSUE TITLE
package with something other than pnpm

### ISSUE THREAD

**Issue by ezpuzz** [drwpow/openapi-fetch#22]
**Description**

Yarn 2 does not install dependencies packaged with pnpm from github, this makes it difficult to fork the package and use the fork directly.

**Proposal**

package using yarn or npm.

**Checklist**

- [ ] I’m willing to open a PR for this (see [CONTRIBUTING.md](https://github.com/drwpow/openapi-fetch/blob/main/CONTRIBUTING.md))

**Comment by ezpuzz** [comment]
https://github.com/yarnpkg/berry/issues/3169

**Comment by drwpow** [comment]
pnpm is a pretty standard library for package maintainers at this point and is arguably used for more new packages than npm/Yarn/Yarn 2. I’m very sorry to hear that GitHub packages hasn’t added support yet for it yet. At this time I’m not supporting installing this from GitHub Packages; only npm.
