### ISSUE TITLE
Post endpoint's data object is typed to union of <SomeType> and <SomeType>[]

### ISSUE THREAD

**Issue by youssefazriouil** [drwpow/openapi-fetch#26]
**Description**

Hi! I'm trying out this package in combination with openapi-typescript. I found that when I tried to POST to my endpoint, let's say `/categories` the type of data is `Category` | `Category[]`, which is weird to me because in my openapi schema, there is no reference to any array being returned from this POST call. What am I doing wrong here?

**Comment by busheezy** [comment]
I'm experiencing pretty much the opposite. I have an endpoint that should only return Item[] but for some reason I get Item | Item[].

**Comment by youssefazriouil** [comment]
@drwpow Is there any way to circumvent this issue?

**Comment by drwpow** [comment]
Just published a new version that fixes several type bugs. Either it fixes this issue, or it at least fixes the blockers to fixing this. Would appreciate if people can try the new version and see if the issue persists.

**Comment by busheezy** [comment]
The problem is still affecting me. I'll work on a reproduction example.

**Comment by drwpow** [comment]
This should be fixed in `v0.1.1`! Thank you for the reproduction—that really helped!
