### ISSUE TITLE
Do not parse as JSON on 204 responses

### ISSUE THREAD

**Issue by nholik** [drwpow/openapi-fetch#27]
**Description**

On 204 response codes should not attempt to call `resp.json()` as a body would be unexpected by most conventions.

**Proposal**

Following [this](https://restfulapi.net/http-status-204-no-content/#:~:text=The%20204%20response%20MUST%20NOT,line%20after%20the%20header%20fields) as one recommendation

I would suggest changing https://github.com/drwpow/openapi-fetch/blob/fabfad203c326c91d7a3107f43ab3e5be95bc4f1/src/index.ts#L142 to something like

```patch
-        return res.ok ? { data: await res.json(), response } : { error: await res.json(), response };
+        return res.ok ? { data: res.status === 204 ? "" : await res.json(), response } : { error: await res.json(), response };
```

or a more sophisticated approach may be on 204 and body length is 0, or a similar strategy.  I would be happy to submit a PR with the suggested change if this line of reasoning sounds okay.

**Checklist**

- [X] I’m willing to open a PR for this (see [CONTRIBUTING.md](https://github.com/drwpow/openapi-fetch/blob/main/CONTRIBUTING.md))

**Comment by drwpow** [comment]
I think this is reasonable! Would definitely accept a PR for this, with one minor change: I’d change the `""` return to `{}`. Mostly so `if (data)` would still work the same as expected runtime wise. But also because an object type in general is a more common response than a string and it may be more predictable to reason about (even if it’s an empty object).

**Comment by nholik** [comment]
@drwpow that makes perfect sense to do `{}`.   I've submitted a PR to that effect https://github.com/drwpow/openapi-fetch/pull/28

**Comment by roj1512** [comment]
Not just 204 responses. There might be reasons to not parse as JSON for any status.
