### ISSUE TITLE
Headers is not assignable to ClientOptions

### ISSUE THREAD

**Issue by darr1s** [drwpow/openapi-fetch#35]
**Description**

It seems like ClientOptions interface did not include any fetch-related options.

<img width="761" alt="image" src="https://user-images.githubusercontent.com/21124691/234704030-fbc9d472-c354-46c3-9437-b86401aa1f26.png">
<img width="832" alt="image" src="https://user-images.githubusercontent.com/21124691/234704034-77f422c9-de24-4f14-bf36-5f56d44bd97e.png">

**Reproduction**

I'm using version 0.0.8

**Expected result**

ClientOptions should extends fetch options.

**Checklist**

- [ ] I’m willing to open a PR (see [CONTRIBUTING.md](https://github.com/drwpow/openapi-fetch/blob/main/CONTRIBUTING.md))

**Comment by drwpow** [comment]
Just published a new version that fixes a number of type issues. Can you see if the issue persists on the new version? Thanks!
