### ISSUE TITLE
Some sort of middleware support

### ISSUE THREAD

**Issue by djMax** [drwpow/openapi-fetch#41]
**Description**

The request interception, response interception, etc is quite useful and I wouldn't think would add much to the library. Is there a way to simulate this on top of the library? (I don't see an obvious one)

**Proposal**

Add a single pre-flight and post-flight hook argument to the methods.

**Checklist**

- [X] I’m willing to open a PR for this (see [CONTRIBUTING.md](https://github.com/drwpow/openapi-fetch/blob/main/CONTRIBUTING.md))

**Comment by drwpow** [comment]
I like the idea in general. But one difficulty to adding this is the type inference. The library gives you types that 100% match your schema, so any middleware transforms would have to basically not transform your types, otherwise your types are unreliable.

Or should the middleware not be transform-based (and if not, what would be a good example)?

**Comment by djMax** [comment]
Yeah, it's an interesting question. I'd think some well placed generic type args probably do what's needed, but it's often more about "fetch like things." i.e. we currently do request timing and telemetry, header manipulation, generic retry handling, and oauth retry handling (got a 401 saying token expire? go run this async function and then try again. got a 403? return the error). It very well may be that this can all be done different ways (for example being able to pass in a fetch function), but if that's the case then the feature is examples/docs.

**Comment by brandonp-ais** [comment]
Just here to say that we use middleware in the same way: for metrics etc., which don't "care" about the types.

Of course it would always be nice to have types available in the middleware, but not imo a hard requirement.

**Comment by drwpow** [comment]
I still want to track this! But since I’m merging this repo in with `openapi-typescript` I’ve moved the discussion [here](https://github.com/drwpow/openapi-typescript/issues/1122).
