### ISSUE TITLE
Wrong types for returns values of some methods

### ISSUE THREAD

**Issue by kwonalbert** [drwpow/openapi-fetch#44]
**Description**

The current typing for return values of `post` and `options` are incorrect. This seems to be just due to the typo in `index.ts` for the type parameters to `coreFetch` for `post` and `options`. (Probably like copy-pasta issue?)

**Reproduction**

Building the current source from master results in wrong return types for `post` and `options`.

**Expected result**

**Checklist**

- [x ] I’m willing to open a PR (see [CONTRIBUTING.md](https://github.com/drwpow/openapi-fetch/blob/main/CONTRIBUTING.md))

(The fix is trivial two line changes, and I'm happy to file the PR though I imagine the authors would be much faster in pushing up the fixes.)

**Comment by drwpow** [comment]
D’oh! Yes that’s just a copypasta error. These types of type errors are so tricky to write tests for, too.

Will push a quick fix now, and think about a good regression test later so this doesn’t happen again.
